### ISSUE TITLE
Params naming rule of `/api/v1/regular_invest`

### ISSUE THREAD

**Issue by wyhfrank** [Chen33D17017/auto-invest-spring#16]
The params for `/api/v1/regular_invest` with method `DELETE` and `PUT` should be in camel case. 

`crypto_name` => `cryptoName`

**Comment by Chen33D17017** [comment]
@wyhfrank 
For delete, because it is on query, I believe snake will be more suitable

**Comment by wyhfrank** [comment]
But think of how you set and get this value. You are treating this value as a variable (just like those variables you got from the reuqest body), instead of parsing the URL path to get the value. Using a naming convention of variables seem more intuitive.

But anyway. For `PUT`, everything should be moved to the request body.
