### ISSUE TITLE
System error when `GET` `/api/v1/user/`

### ISSUE THREAD

**Issue by wyhfrank** [Chen33D17017/auto-invest-spring#19]
Error message: 

``` json
{
    "data": "system error",
    "resultInfo": {
        "codeId": "00000900",
        "code": "SYSTEM_ERROR",
        "message": "System error",
        "status": "F"
    }
}
```

**Comment by wyhfrank** [comment]
It seems that this only occurs in my local environment. Is it related to the inconsistent state of my server database?

**Comment by Chen33D17017** [comment]
Could you provide me the error message from server side logs next time ?
This may cause be several reason

**Comment by wyhfrank** [comment]
The problem is there is not server log. You didn't print anything when this exception occurs.

Code:

https://github.com/Chen33D17017/auto-invest-spring/blob/main/src/main/java/me/peihao/autoInvest/filter/CustomAuthorizationFilter.java#L59

Log:

``` log
2022-02-28 18:30:58.423  INFO 1 --- [nio-8080-exec-3] m.p.a.f.CustomizeAuthenticationFilter    : User micy is trying to login
```
